# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 15:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180128_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='items',
            field=wagtail.wagtailcore.fields.StreamField([(b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.CharBlock(required=False))]))]),
        ),
    ]
