# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180211_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='hit',
            field=models.IntegerField(blank=True, null=True, verbose_name='rating'),
        ),
    ]
