# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 12:09
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='carousel',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
