# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 15:17
from __future__ import unicode_literals

import blog.blocks
from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'size', wagtail.wagtailcore.blocks.ChoiceBlock(blank=True, choices=[(b'h2', b'H2'), (b'h3', b'H3'), (b'h4', b'H4'), (b'h5', b'H5'), (b'h6', b'H6')], required=False))])), (b'paragraph', blog.blocks.CustomRichTextBlock(features=[b'bold', b'italic', b'ol', b'ul', b'hr', b'link', b'document-link'])), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'caaption', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'attribute', wagtail.wagtailcore.blocks.CharBlock(required=False))])), (b'blockquote', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.TextBlock()), (b'attribute', wagtail.wagtailcore.blocks.CharBlock(blank=True, required=False))])), (b'embed', wagtail.wagtailembeds.blocks.EmbedBlock()), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), (b'code', wagtail.wagtailcore.blocks.StructBlock([(b'language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'python', b'Python'), (b'html', b'HTML'), (b'css', b'CSS'), (b'scss', b'SCSS'), (b'json', b'JSON')])), (b'style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'syntax', b'default'), (b'monokai', b'monokai'), (b'xcode', b'xcode')])), (b'code', wagtail.wagtailcore.blocks.TextBlock())])), (b'raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, verbose_name='Body'),
        ),
    ]
